<a href="https://colab.research.google.com/github/jdalvaradocol/EIA_DL/blob/main/Clase2ej1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

def funcion_activacion(entrada)

    size = len(entrada)

    salida = np.zeros((size,1))

    for i in range(size)

        if entrada[i,0] >= 0

          salida[i,0] = 1

    return salida
## Entradas x1 x2 x3

x1 = 1
x2 = 0
x3 = 0

umbral = 3

W = np.array([1 , 1 , 1])

X = np.array([x1 , x2 , x3])

print('\n X \n',X)
print('\n W \n',W)

y = np.dot(np.transpose(W),X)

print('\n y \n',y)

if (y >= umbral):
    print('Asistiremos a cine')
else:
    print('No asistiremos a cine')



 X 
 [1 0 0]

 W 
 [1 1 1]

 y 
 1
No asistiremos a cine


In [17]:
# Clasificador de la compuerta OR

bias = 1
x1 = 0
x2 = 0

X = np.array([[bias],[x1],[x2]])

print('\n X \n',X)

WOR   = np.array([[-0.5],[ 1],[ 1]])
WNAND = np.array([[ 1.5],[-1],[-1]])
WAND  = np.array([[-1.5],[ 1],[ 1]])

W1 = np.zeros((3,2))

W1[:,0] = WOR[:,0]
W1[:,1] = WNAND[:,0]

print('\n W1 \n',W1)

W2 = WAND
print('\n W2 \n',W2)


 X 
 [[1]
 [0]
 [0]]

 W1 
 [[-0.5  1.5]
 [ 1.  -1. ]
 [ 1.  -1. ]]

 W2 
 [[-1.5]
 [ 1. ]
 [ 1. ]]


In [19]:
y1 = np.dot(np.transpose(W1),X)
print('\n y1 \n',y1)


 y1 
 [[-0.5]
 [ 1.5]]


In [ ]:
# funcion de activacion

